namespace AbpBlazorCustomizeLoginPage;

public abstract class AbpBlazorCustomizeLoginPageApplicationTestBase : AbpBlazorCustomizeLoginPageTestBase<AbpBlazorCustomizeLoginPageApplicationTestModule>
{

}
